apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flagger-discord-webhook
  namespace: backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault
  target:
    name: flagger-discord-webhook
    creationPolicy: Owner
  data:
    - secretKey: address
      remoteRef:
        key: DISCORD_ALERTS_WEBHOOK_URL
