apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - source.yaml
  - base.yaml
  - istiod.yaml
  - cni.yaml
  - ztunnel.yaml
  - gateway.yaml
  - gateway-authz.yaml
  - cluster-issuer.yaml
  - http-redirect.yaml
  - cilium-hostprobes.yaml
