. (Join-Path $PSScriptRoot "gitops-test-helpers.ps1")

$observability = (Build-Kustomization "gitops/infrastructure/observability") -replace "`r`n", "`n"
$certManager = (Build-Kustomization "gitops/infrastructure/cert-manager") -replace "`r`n", "`n"
$infrastructure = (Read-RepoFile "gitops/clusters/production/infrastructure.yaml") -replace "`r`n", "`n"
$monitoringNamespace = Get-RenderedResource -Rendered $observability -Kind "Namespace"
$certManagerNamespace = Get-RenderedResource -Rendered $certManager -Kind "Namespace"
$alertmanagerValues = [regex]::Match($observability, "(?ms)^    alertmanager:`n.*?(?=^    [a-zA-Z]|\z)").Value
$alertmanagerSpec = [regex]::Match($observability, "(?ms)^      alertmanagerSpec:`n.*?(?=^      [a-zA-Z]|\z)").Value
$alertmanagerConfig = Get-RenderedResourceByName -Rendered $observability -Kind "AlertmanagerConfig" -Name "platform-alertmanager"
$alertmanagerRoute = [regex]::Match($alertmanagerConfig, '(?ms)^  route:\n.*\z').Value
$alertmanagerRootRoute = [regex]::Match($alertmanagerRoute, '(?ms)^  route:\n.*?(?=^    routes:)').Value
$alertmanagerChildRoutes = [regex]::Match($alertmanagerRoute, '(?ms)^    routes:\n.*\z').Value
$alertmanagerPolicy = [regex]::Match(
    $observability,
    "(?ms)^apiVersion: cilium\.io/v2`nkind: CiliumNetworkPolicy`nmetadata:`n  name: alertmanager`n.*?(?=^---`n|\z)"
).Value
$certManagerPolicy = [regex]::Match(
    $certManager,
    "(?ms)^apiVersion: cilium\.io/v2`nkind: CiliumNetworkPolicy`nmetadata:`n  name: cert-manager-controller`n.*?(?=^---`n|\z)"
).Value
$certManagerApiEgress = [regex]::Match(
    $certManagerPolicy,
    '(?ms)^  - toEntities:\n.*?(?=^  - to(?:Endpoints|Entities|FQDNs):|\z)'
).Value
$alertmanagerAuthorization = Get-RenderedResourceByName -Rendered $observability -Kind "AuthorizationPolicy" -Name "allow-prometheus-to-alertmanager"
$prometheusAuthorization = Get-RenderedResourceByName -Rendered $observability -Kind "AuthorizationPolicy" -Name "allow-observability-clients-to-prometheus"
$certManagerAuthorization = Get-RenderedResourceByName -Rendered $observability -Kind "AuthorizationPolicy" -Name "allow-prometheus-to-cert-manager"

Assert-Matches $observability "(?m)^kind: Namespace$" "monitoring namespace must exist before secrets"
Assert-Matches $observability "(?m)^  name: monitoring$" "Alertmanager resources must target monitoring"
Assert-Matches $monitoringNamespace "(?m)^\s+istio\.io/dataplane-mode: ambient$" "monitoring workloads must use Ambient mTLS"
Assert-Matches $certManagerNamespace "(?m)^\s+istio\.io/dataplane-mode: ambient$" "cert-manager workloads must use Ambient mTLS"
Assert-Matches $observability "(?m)^\s+key: DISCORD_ALERTS_WEBHOOK_URL$" "Alertmanager must use the approved Vault key"
Assert-Matches $observability "(?ms)alertmanager:.*?enabled: true" "Alertmanager must be enabled"
Assert-Matches $observability "(?ms)alertmanagerSpec:.*?replicas: 1" "Alertmanager must use exactly one replica"
Assert-Matches $observability "(?m)^        retention: 24h$" "retention must remain minimal"
Assert-Matches $observability "(?ms)alertmanagerSpec:.*?resources:.*?requests:.*?cpu: 10m.*?memory: 32Mi.*?limits:.*?memory: 128Mi" "Alertmanager must fit the budget"
Assert-Matches $alertmanagerValues "(?ms)^      serviceAccount:`n.*?^        automountServiceAccountToken: false$" "Alertmanager service account must not mount an API token"
Assert-Matches $alertmanagerSpec "(?m)^        automountServiceAccountToken: false$" "Alertmanager pods must not mount an API token"
Assert-NoMatches $alertmanagerSpec "(?m)^\s+(storage:|volumeClaimTemplate:|volumeClaimTemplates:)" "Alertmanager must not request a PVC"
Assert-MatchCount $observability "(?m)^kind: AlertmanagerConfig$" 1 "observability must define exactly one AlertmanagerConfig"
Assert-Matches $alertmanagerSpec "(?ms)alertmanagerConfiguration:.*?name: platform-alertmanager" "Alertmanager must select the global configuration"
Assert-Matches $alertmanagerSpec "(?m)^\s+resolveTimeout: 5m$" "the global resolve timeout must be preserved"
Assert-Matches $alertmanagerSpec "(?ms)alertmanagerConfigSelector:.*?matchLabels:.*?alerting\.aienterprise\.io/role: supplemental" "only explicitly labeled supplemental configurations may be merged"
Assert-Matches $alertmanagerSpec "(?ms)alertmanagerConfigNamespaceSelector:.*?matchLabels:.*?kubernetes\.io/metadata\.name: monitoring" "supplemental configurations must stay in monitoring"
Assert-NoMatches $alertmanagerConfig "alerting\.aienterprise\.io/role" "the global configuration must not be selected as supplemental"
Assert-NoMatches $alertmanagerSpec "(?m)^\s+secrets:" "Alertmanager must not mount the webhook as a file"
Assert-Matches $alertmanagerConfig "(?ms)apiURL:.*?key: address.*?name: alertmanager-discord-webhook" "Discord must select the Vault-backed Secret key"
Assert-Matches $alertmanagerConfig "(?m)^\s+sendResolved: true$" "resolved alerts must be delivered"
Assert-Matches $alertmanagerRootRoute '(?m)^    receiver: discord$' "unknown warnings and critical alerts must default to Discord"
Assert-MatchCount $alertmanagerRootRoute '(?m)^    - namespace$' 1 "root alerts must group by namespace"
Assert-NoMatches $alertmanagerRootRoute '(?m)^    - alertname$' "root grouping must coalesce related alert names"
Assert-Matches $alertmanagerRootRoute '(?m)^    groupWait: 2m$' "warnings must wait two minutes for related symptoms"
Assert-Matches $alertmanagerRootRoute '(?m)^    groupInterval: 5m$' "notification group interval must remain five minutes"
Assert-Matches $alertmanagerRootRoute '(?m)^    repeatInterval: 12h$' "warnings must repeat no more than twice daily"
Assert-MatchCount $alertmanagerChildRoutes '(?m)^      receiver: "null"$' 3 "only three child routes may discard alerts"
Assert-Matches $alertmanagerChildRoutes '(?ms)name: alertname\n\s+value: Watchdog\n\s+receiver: "null"' "Watchdog must route to null"
Assert-Matches $alertmanagerChildRoutes '(?ms)name: severity\n\s+value: info\n\s+receiver: "null"' "informational alerts must route directly to null"
Assert-Matches $alertmanagerChildRoutes '(?ms)matchType: =~\n\s+name: alertname\n\s+value: KubeCPUOvercommit\|KubeMemoryOvercommit\n\s+receiver: "null"' "only the structural overcommit alerts must route to null"
Assert-Matches $alertmanagerChildRoutes '(?ms)groupWait: 30s.*?name: severity\n\s+value: critical\n\s+receiver: discord\n\s+repeatInterval: 4h' "critical alerts must retain fast delivery and repetition"
Assert-MatchCount $alertmanagerRoute '(?m)^[ \t]+- groupWait: 30s\r?$' 1 "only critical alerts may use the short wait"
Assert-MatchCount $alertmanagerRoute '(?m)^[ \t]+repeatInterval: 4h\r?$' 1 "only critical alerts may use the short repeat"
Assert-MatchCount $alertmanagerConfig "(?m)^\s+(?:-\s+)?sourceMatch:$" 3 "the three source-based inhibition rules must remain"
Assert-MatchCount $alertmanagerConfig "(?m)^\s+(?:-\s+)?targetMatch:$" 4 "all four inhibition targets must remain"
Assert-Matches $alertmanagerConfig "(?ms)sourceMatch:.*?value: critical.*?targetMatch:.*?value: warning\|info" "critical alerts must inhibit warning and info alerts"
Assert-NoMatches $observability "webhook_url_file|webhookUrlFile" "unsupported file-backed Discord fields must not return"
Assert-NoMatches $observability "https://discord\.com/api/webhooks/" "No Webhook URL may be committed"
Assert-Matches $observability "(?m)^\s+- alert: NodeCPURequestsHigh$" "node saturation rule must exist"
Assert-Matches $observability "0\.95" "node CPU threshold must be 95 percent"
Assert-Matches $observability 'kube_pod_status_phase\{phase=~"Pending\|Running"\}' "node CPU requests must exclude terminal pods"
Assert-Matches $observability '\* on \(namespace, pod, uid\) group_left\(\)' "active-pod filtering must bind to the exact Pod UID"
Assert-Matches $observability "(?m)^\s+- alert: CertificateExpiringSoon$" "certificate rule must exist"
Assert-Matches $observability "1814400" "certificate window must be 21 days"
Assert-Matches $observability "(?m)^\s+- alert: FlaggerCanaryFailed$" "persistent Flagger rule must exist"
Assert-Matches $observability "flagger_canary_status > 1" "official Flagger failed-state expression must be used"
Assert-NoMatches $observability "(?m)^\s+- alert: KubePodCrashLooping$" "KubePodCrashLooping must remain chart-provided"
Assert-Matches $observability "(?m)^\s+release: kube-prometheus-stack$" "rules must match Prometheus selectors"
if ($alertmanagerPolicy.Length -eq 0) {
    throw "[ASSERT] Alertmanager needs a dedicated Cilium policy"
}
Assert-Matches $alertmanagerPolicy "(?ms)endpointSelector:.*?alertmanager: kube-prometheus-stack-alertmanager" "CNP must select the Alertmanager instance"
Assert-Matches $alertmanagerPolicy "(?ms)endpointSelector:.*?app\.kubernetes\.io/name: alertmanager" "CNP must select only Alertmanager pods"
Assert-MatchCount $alertmanagerPolicy "(?m)^\s+- fromEndpoints:$" 1 "Alertmanager must have exactly one Prometheus ingress source"
Assert-MatchCount $alertmanagerPolicy "(?m)^\s+- toEndpoints:$" 1 "Alertmanager must have exactly one DNS endpoint egress"
Assert-MatchCount $alertmanagerPolicy "(?m)^\s+- toFQDNs:$" 1 "Alertmanager must have exactly one Discord egress"
Assert-NoMatches $alertmanagerPolicy "(?m)^\s+- to(?:CIDR|CIDRSet|Entities|Services):$" "Alertmanager must not have another egress destination family"
Assert-Matches $alertmanagerPolicy "(?ms)toEndpoints:.*?k8s-app: kube-dns" "CNP DNS egress must select kube-dns"
Assert-Matches $alertmanagerPolicy "(?ms)toEndpoints:.*?k8s:io\.kubernetes\.pod\.namespace: kube-system" "CNP DNS egress must stay in kube-system"
Assert-MatchCount $alertmanagerPolicy "(?m)^\s+- matchName: discord\.com$" 1 "Alertmanager egress must target only Discord"
Assert-MatchCount $alertmanagerPolicy '(?m)^\s+- port: "53"$' 2 "DNS egress must expose TCP and UDP 53 only"
Assert-MatchCount $alertmanagerPolicy '(?m)^\s+- port: "443"$' 1 "Discord egress must use HTTPS only"
Assert-MatchCount $alertmanagerPolicy '(?m)^\s+- port: "9093"$' 1 "Prometheus must reach Alertmanager only once"
Assert-MatchCount $alertmanagerPolicy '(?m)^\s+- port: "8080"$' 1 "Prometheus must reach config-reloader metrics only once"
Assert-MatchCount $alertmanagerPolicy '(?m)^\s+- port: "15008"$' 1 "Alertmanager must accept Ambient HBONE"
Assert-MatchCount $alertmanagerPolicy '(?m)^\s+- port: "[^\"]+"$' 6 "Alertmanager policy must contain no extra ports"
Assert-Matches $alertmanagerPolicy '(?ms)ingress:.*?app\.kubernetes\.io/name: prometheus' "Alertmanager ingress must select Prometheus pods"
Assert-Matches $alertmanagerPolicy '(?ms)ingress:.*?prometheus: kube-prometheus-stack-prometheus' "Alertmanager ingress must select the Prometheus instance"
Assert-Matches $alertmanagerPolicy '(?ms)ingress:.*?k8s:io\.kubernetes\.pod\.namespace: monitoring' "Alertmanager ingress must stay in monitoring"
Assert-Matches $alertmanagerPolicy '(?ms)ingress:.*?port: "9093".*?port: "8080"' "Prometheus may reach only Alertmanager ports 9093 and 8080"
Assert-MatchCount $observability "(?m)^kind: AuthorizationPolicy$" 3 "observability must define exactly three workload-identity policies"
Assert-Matches $alertmanagerAuthorization "(?ms)selector:.*?alertmanager: kube-prometheus-stack-alertmanager.*?app\.kubernetes\.io/name: alertmanager" "Alertmanager identity policy must select only Alertmanager"
Assert-MatchCount $alertmanagerAuthorization "(?m)^\s+- monitoring/kube-prometheus-stack-prometheus$" 1 "only the Prometheus service account may reach Alertmanager"
Assert-MatchCount $alertmanagerAuthorization '(?m)^\s+- "(?:8080|9093)"$' 2 "Alertmanager identity policy must allow only its two service ports"
Assert-Matches $prometheusAuthorization "(?ms)selector:.*?app\.kubernetes\.io/name: prometheus.*?prometheus: kube-prometheus-stack-prometheus" "Prometheus identity policy must select only Prometheus"
Assert-MatchCount $prometheusAuthorization "(?m)^\s+- (?:flagger-system/flagger|monitoring/kube-prometheus-stack-grafana|monitoring/kube-prometheus-stack-prometheus)$" 3 "Prometheus must accept only its known in-mesh clients"
Assert-MatchCount $prometheusAuthorization '(?m)^\s+- "9090"$' 1 "Prometheus identity policy must expose only port 9090"
Assert-Matches $certManagerAuthorization "(?ms)selector:.*?app\.kubernetes\.io/component: controller.*?app\.kubernetes\.io/instance: cert-manager.*?app\.kubernetes\.io/name: cert-manager" "cert-manager identity policy must select only the controller"
Assert-MatchCount $certManagerAuthorization "(?m)^\s+- monitoring/kube-prometheus-stack-prometheus$" 1 "only Prometheus may reach cert-manager metrics"
Assert-MatchCount $certManagerAuthorization '(?m)^\s+- "9402"$' 1 "cert-manager identity policy must expose only metrics port 9402"
Assert-Matches $certManager "(?ms)servicemonitor:.*?enabled: true.*?release: kube-prometheus-stack" "cert-manager metrics must be selected"
Assert-Matches $certManager "(?ms)servicemonitor:.*?honorLabels: true" "cert-manager certificate labels must survive scraping"
Assert-Matches $certManager "(?ms)servicemonitor:.*?endpointAdditionalProperties:.*?relabelings:" "cert-manager ServiceMonitor must filter discovery targets"
Assert-Matches $certManager "__meta_kubernetes_service_label_app_kubernetes_io_component" "cert-manager target filtering must use the component label"
Assert-Matches $certManager "(?m)^\s+regex: controller$" "only the cert-manager controller may be scraped"
Assert-Matches $certManager "(?m)^\s+- action: keep$" "non-controller cert-manager targets must be dropped"
if ($certManagerPolicy.Length -eq 0) {
    throw "[ASSERT] cert-manager controller needs a dedicated Cilium policy"
}
if ($certManagerApiEgress.Length -eq 0) {
    throw "[ASSERT] cert-manager needs a Kubernetes API egress block"
}
Assert-Matches $certManagerPolicy "(?ms)endpointSelector:.*?app\.kubernetes\.io/component: controller.*?app\.kubernetes\.io/instance: cert-manager.*?app\.kubernetes\.io/name: cert-manager" "CNP must select only the cert-manager controller"
Assert-MatchCount $certManagerPolicy "(?m)^\s+- fromEndpoints:$" 1 "cert-manager must have exactly one metrics ingress source"
Assert-Matches $certManagerPolicy "(?ms)ingress:.*?app\.kubernetes\.io/name: prometheus" "cert-manager metrics ingress must select Prometheus pods"
Assert-Matches $certManagerPolicy "(?ms)ingress:.*?prometheus: kube-prometheus-stack-prometheus" "cert-manager metrics ingress must select the Prometheus instance"
Assert-Matches $certManagerPolicy "(?ms)ingress:.*?k8s:io\.kubernetes\.pod\.namespace: monitoring" "cert-manager metrics ingress must stay in monitoring"
Assert-MatchCount $certManagerPolicy '(?m)^\s+- port: "9402"$' 1 "cert-manager metrics ingress must use only port 9402"
Assert-MatchCount $certManagerPolicy "(?m)^\s+- toEndpoints:$" 1 "cert-manager must have exactly one DNS endpoint egress"
Assert-MatchCount $certManagerPolicy "(?m)^\s+- toEntities:$" 1 "cert-manager must have exactly one Kubernetes API egress"
Assert-MatchCount $certManagerPolicy "(?m)^\s+- toFQDNs:$" 2 "cert-manager must have exactly two external egress rule families"
Assert-MatchCount $certManagerPolicy "(?m)^\s+- to(?:Endpoints|Entities|FQDNs):$" 4 "cert-manager must contain only intended egress rule families"
Assert-NoMatches $certManagerPolicy "(?m)^\s+- to(?:CIDR|CIDRSet|Services):$" "cert-manager must not have another egress destination family"
Assert-MatchCount $certManagerPolicy "(?m)^\s+- matchName: (?:acme-v02\.api\.letsencrypt\.org|acme\.zerossl\.com|ai-auto\.kro\.kr|api\.ai-auto\.kro\.kr)$" 4 "cert-manager external destinations must be exact"
Assert-MatchCount $certManagerPolicy "(?m)^\s+- matchName: .+$" 4 "cert-manager must not have extra FQDN destinations"
Assert-MatchCount $certManagerPolicy "(?m)^\s+- kube-apiserver$" 1 "cert-manager must reach only the Kubernetes API entity"
Assert-MatchCount $certManagerPolicy "(?m)^\s+- (?:all|world|cluster|host|init|ingress|unmanaged|remote-node|health|kube-apiserver|none)$" 1 "cert-manager must not allow another Cilium entity"
Assert-MatchCount $certManagerApiEgress '(?m)^      - port: "443"$' 1 "cert-manager API egress must preserve the Service port"
Assert-MatchCount $certManagerApiEgress '(?m)^      - port: "6443"$' 1 "cert-manager API egress must allow the observed OKE backend port"
Assert-MatchCount $certManagerApiEgress '(?m)^        protocol: TCP$' 2 "cert-manager API egress must contain only two TCP ports"
Assert-MatchCount $certManagerPolicy '(?m)^      - port: "6443"$' 1 "cert-manager must expose the OKE API backend port only once"
Assert-MatchCount $certManagerPolicy '(?m)^\s+- port: "53"$' 2 "cert-manager DNS must use TCP and UDP 53"
Assert-MatchCount $certManagerPolicy '(?m)^\s+- port: "443"$' 2 "cert-manager API and ACME traffic must use HTTPS"
Assert-MatchCount $certManagerPolicy '(?m)^\s+- port: "80"$' 1 "HTTP-01 self-checks must use the public HTTP listener"
Assert-MatchCount $certManagerPolicy '(?m)^\s+- port: "15008"$' 1 "cert-manager must accept Ambient HBONE"
Assert-MatchCount $certManagerPolicy '(?m)^\s+- port: "[^\"]+"$' 8 "cert-manager policy must contain no extra ports"
Assert-Matches $infrastructure "(?ms)name: infra-observability.*?dependsOn:.*?name: infra-istio-ambient.*?name: security-external-secrets" "observability must wait for Vault access"

Write-Host "Runtime alerting contracts passed"
