apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: platform-alertmanager
  namespace: monitoring
spec:
  route:
    receiver: discord
    groupBy:
      - namespace
    groupWait: 2m
    groupInterval: 5m
    repeatInterval: 12h
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            matchType: "="
            value: Watchdog
      - receiver: "null"
        matchers:
          - name: severity
            matchType: "="
            value: info
      - receiver: "null"
        matchers:
          - name: alertname
            matchType: "=~"
            value: KubeCPUOvercommit|KubeMemoryOvercommit
      - receiver: discord
        groupWait: 30s
        repeatInterval: 4h
        matchers:
          - name: severity
            matchType: "="
            value: critical
  inhibitRules:
    - sourceMatch:
        - name: severity
          matchType: "="
          value: critical
      targetMatch:
        - name: severity
          matchType: "=~"
          value: warning|info
      equal: [namespace, alertname]
    - sourceMatch:
        - name: severity
          matchType: "="
          value: warning
      targetMatch:
        - name: severity
          matchType: "="
          value: info
      equal: [namespace, alertname]
    - sourceMatch:
        - name: alertname
          matchType: "="
          value: InfoInhibitor
      targetMatch:
        - name: severity
          matchType: "="
          value: info
      equal: [namespace]
    - targetMatch:
        - name: alertname
          matchType: "="
          value: InfoInhibitor
  receivers:
    - name: "null"
    - name: discord
      discordConfigs:
        - apiURL:
            name: alertmanager-discord-webhook
            key: address
          sendResolved: true
